### ISSUE TITLE
Mute call

### ISSUE THREAD

**Issue by reallyseth** [twilio/voice-callkit-quickstart-swift#9]
Hi, I'm working on adding a mute call button into my app. I originally thought I could just call `VoiceClient.sharedInstance().stopAudioDevice()` to mute the call, but that doesn't seem to work. Is there a way using the SDK, or otherwise, to mute an active call?

Thanks so much for the help!

**Comment by reallyseth** [comment]
Ooops, posted on the wrong repo. Sorry!

**Comment by bchen-twilio** [comment]
Man! I am in the middle of replying :p
